import { StyleSheet } from 'react-native';

export const voiceStyles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#0f172a',
    },
    background: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
    },
    safeArea: {
        flex: 1,
        alignItems: 'center',
        paddingHorizontal: 20,
    },
    header: {
        marginTop: 20,
        marginBottom: 40,
        alignItems: 'center',
    },
    headerText: {
        fontSize: 18,
        color: 'rgba(255,255,255,0.6)',
        fontWeight: '600',
        textTransform: 'uppercase',
        letterSpacing: 2,
    },
    connectedBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        marginTop: 8,
        backgroundColor: 'rgba(16, 185, 129, 0.2)',
        paddingHorizontal: 12,
        paddingVertical: 4,
        borderRadius: 12,
    },
    connectedDot: {
        width: 8,
        height: 8,
        borderRadius: 4,
        backgroundColor: '#10b981',
        marginRight: 6,
    },
    connectedText: {
        color: '#10b981',
        fontSize: 12,
        fontWeight: '500',
    },
    orbContainer: {
        width: 200,
        height: 200,
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 30,
    },
    orb: {
        width: 180,
        height: 180,
        borderRadius: 90,
        shadowColor: "#4f46e5",
        shadowOffset: { width: 0, height: 0 },
        shadowOpacity: 0.6,
        shadowRadius: 40,
        elevation: 20,
    },
    orbIconOverlay: {
        position: 'absolute',
        justifyContent: 'center',
        alignItems: 'center',
    },
    statusText: {
        color: 'rgba(255,255,255,0.5)',
        fontSize: 16,
        marginBottom: 20,
        fontWeight: '500',
    },
    responseContainer: {
        flexGrow: 1,
        width: '100%',
        alignItems: 'center',
        paddingVertical: 10,
    },
    responseText: {
        color: '#fff',
        fontSize: 24,
        fontWeight: '500',
        textAlign: 'center',
        lineHeight: 34,
        textShadowColor: 'rgba(0,0,0,0.5)',
        textShadowOffset: { width: 0, height: 2 },
        textShadowRadius: 4,
    },
    controls: {
        marginTop: 20,
        marginBottom: 20,
    },
    micButton: {
        width: 80,
        height: 80,
        borderRadius: 40,
        elevation: 10,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.5,
        shadowRadius: 5,
    },
    micButtonGradient: {
        width: '100%',
        height: '100%',
        borderRadius: 40,
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 2,
        borderColor: 'rgba(255,255,255,0.2)',
    },
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.7)',
        justifyContent: 'center',
        alignItems: 'center',
        padding: 20,
    },
    confirmCard: {
        width: '85%',
        backgroundColor: '#1e293b',
        borderRadius: 16,
        padding: 20,
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.1)',
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 10 },
        shadowOpacity: 0.5,
        shadowRadius: 20,
        elevation: 10,
    },
    confirmHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 10,
        gap: 10,
    },
    confirmTitle: {
        color: '#f59e0b',
        fontWeight: 'bold',
        fontSize: 16,
        textTransform: 'uppercase',
    },
    confirmMessage: {
        color: 'white',
        fontSize: 18,
        marginBottom: 20,
        lineHeight: 26,
    },
    confirmButtons: {
        flexDirection: 'row',
        gap: 15,
    },
    optionItem: {
        padding: 15,
        borderBottomWidth: 1,
        borderBottomColor: 'rgba(255,255,255,0.1)',
        backgroundColor: 'rgba(255,255,255,0.05)',
    },
    optionText: {
        color: '#fff',
        fontSize: 16,
    },
    btn: {
        flex: 1,
        height: 50,
        borderRadius: 25,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'rgba(255,255,255,0.1)',
    },
    btnConfirm: {
        backgroundColor: 'transparent',
        overflow: 'hidden',
    },
    btnGradient: {
        width: '100%',
        height: '100%',
        justifyContent: 'center',
        alignItems: 'center',
    },
    btnText: {
        color: '#fff',
        fontWeight: '600',
        fontSize: 16,
    },
    btnTextWhite: {
        color: '#fff',
        fontWeight: 'bold',
        fontSize: 16,
    },
    btnCancel: {
        backgroundColor: 'rgba(255, 255, 255, 0.08)',
    },
    userBubble: {
        backgroundColor: 'rgba(79, 70, 229, 0.3)',
        paddingHorizontal: 16,
        paddingVertical: 10,
        borderRadius: 20,
        marginBottom: 16,
        alignSelf: 'flex-end',
        maxWidth: '80%',
        borderWidth: 1,
        borderColor: 'rgba(129, 140, 248, 0.3)',
    },
    userBubbleText: {
        color: '#c7d2fe',
        fontSize: 16,
        fontStyle: 'italic',
    },
    thinkingContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
        marginTop: 10,
    },
    thinkingText: {
        color: 'rgba(255,255,255,0.6)',
        fontSize: 14,
    },
    startButton: {
        width: 160,
        height: 60,
        borderRadius: 30,
        elevation: 10,
        shadowColor: '#10b981',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.5,
        shadowRadius: 10,
    },
    sessionButtonGradient: {
        width: '100%',
        height: '100%',
        borderRadius: 30,
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        gap: 8,
    },
    sessionButtonText: {
        color: 'white',
        fontWeight: 'bold',
        fontSize: 18,
    },
    sessionActiveControls: {
        alignItems: 'center',
        gap: 12,
    },
    holdHint: {
        color: 'rgba(255,255,255,0.5)',
        fontSize: 14,
    },
    stopButton: {
        marginTop: 10,
    },
});
